-- AlterEnum
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'LABEL_CREATED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PENDING_LABEL';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PACKAGE_RECEIVED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'ON_THE_WAY';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PICK_UP';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'DELIVERY';
