"use client";

import { VisualDiffViewer } from "@admin/app/(main)/system/audit-logs/AuditLogsContent";
import { useToast } from "@admin/components/toast-provider";
import { trpc } from "@admin/lib/trpc";
import { formatDateTime } from "@admin/utils/dateFormat";
import type { ContentStatus, RateCardType, ShippingMethod } from "@ecom/prisma";
import { Badge } from "@ecom/ui/components/badge";
import { Button } from "@ecom/ui/components/button";
import { Card, CardContent } from "@ecom/ui/components/card";
import { DatePicker } from "@ecom/ui/components/date-picker";
import { Input } from "@ecom/ui/components/input";
import { Label } from "@ecom/ui/components/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@ecom/ui/components/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@ecom/ui/components/tabs";
import { cn } from "@ecom/ui/lib/utils";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  AlertCircle,
  ArrowLeft,
  CheckCircle,
  ChevronLeft,
  Download,
  History,
  Info,
  Loader2,
  Plus,
  Save,
  Scale,
  Trash2,
  Upload,
  Users,
  Wand2,
} from "lucide-react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useTranslations } from "next-intl";
import { useCallback, useEffect, useMemo, useState } from "react";
import type {
  Control,
  FieldErrors,
  UseFormRegister,
  UseFormSetValue,
  UseFormWatch,
} from "react-hook-form";
import { Controller, useForm } from "react-hook-form";
import { z } from "zod";

interface RateCardFormProps {
  rateCardId: number | null;
}

type SlabItem = {
  startWeight: number;
  endWeight: number;
  rateType: "STEP_FIXED" | "RANGE_FIXED" | "RANGE_PER_KG";
  amount: number;
  isAutoGenerated?: boolean;
  keyId: string;
};

function parseCSVRows(text: string, invalidNumMsgFn: (line: number) => string): SlabItem[] {
  const lines = text.split(/\r?\n/);
  const imported: SlabItem[] = [];
  for (let i = 1; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) continue;
    const parts = line.split(",");
    if (parts.length < 4) continue;
    const sw = Number.parseFloat(parts[0]);
    const ew = Number.parseFloat(parts[1]);
    const rt = parts[2].trim() as SlabItem["rateType"];
    const amt = Number.parseFloat(parts[3]);
    if (Number.isNaN(sw) || Number.isNaN(ew) || Number.isNaN(amt)) {
      throw new Error(invalidNumMsgFn(i + 1));
    }
    imported.push({
      startWeight: sw,
      endWeight: ew,
      rateType: ["STEP_FIXED", "RANGE_FIXED", "RANGE_PER_KG"].includes(rt) ? rt : "STEP_FIXED",
      amount: amt,
      isAutoGenerated: false,
      keyId: `${sw}-${ew}-${Math.random()}`,
    });
  }
  return imported;
}

function checkSlabContiguityAndMonotonicity(prev: SlabItem, curr: SlabItem, index: number) {
  if (curr.startWeight !== prev.endWeight) {
    throw new Error(
      `Khoảng cân hở ở dòng ${index + 2}: Nấc tiếp theo bắt đầu (${curr.startWeight}kg) không khớp với nấc trước kết thúc (${prev.endWeight}kg).`,
    );
  }
  const prevCost = prev.rateType === "RANGE_PER_KG" ? prev.endWeight * prev.amount : prev.amount;
  const currCost = curr.rateType === "RANGE_PER_KG" ? curr.startWeight * curr.amount : curr.amount;
  if (currCost < prevCost) {
    throw new Error(
      `Vi phạm tính đơn điệu ở dòng ${index + 2}: Giá cước nấc sau (${currCost.toFixed(2)}) nhỏ hơn nấc trước (${prevCost.toFixed(2)}).`,
    );
  }
}

function validateCSVSlabs(imported: SlabItem[]) {
  for (let i = 0; i < imported.length; i++) {
    const curr = imported[i];
    if (curr.startWeight >= curr.endWeight) {
      throw new Error(
        `Nấc cước dòng ${i + 2}: Trọng lượng bắt đầu (${curr.startWeight}kg) phải nhỏ hơn kết thúc (${curr.endWeight}kg).`,
      );
    }
    if (i > 0) {
      checkSlabContiguityAndMonotonicity(imported[i - 1], curr, i);
    }
  }
}

function parseAndValidateCSVText(
  text: string,
  invalidNumMsgFn: (line: number) => string,
): SlabItem[] {
  const imported = parseCSVRows(text, invalidNumMsgFn);
  imported.sort((a, b) => a.startWeight - b.startWeight);
  validateCSVSlabs(imported);
  return imported;
}

const INITIAL_FORM_STATE = {
  code: "",
  name: "",
  type: "DEFAULT" as RateCardType,
  status: "DRAFT" as ContentStatus,
  shippingMethod: "EXPRESS" as ShippingMethod,
  country: "US",
  origin: "",
  currency: "USD",
  weightStep: 0.5,
  minWeight: 0.0,
  maxWeight: 10.0,
  startDate: "",
  endDate: "",
};

const rateCardFormSchema = z
  .object({
    code: z.string().trim().min(1, "rates.validationRequiredCode"),
    name: z.string().trim().min(1, "rates.validationRequiredName"),
    type: z.custom<RateCardType>(),
    status: z.custom<ContentStatus>(),
    shippingMethod: z.custom<ShippingMethod>(),
    country: z.string(),
    origin: z.string(),
    currency: z.string(),
    weightStep: z.number().positive("rates.validationWeightStep"),
    minWeight: z.number().nonnegative("rates.validationMinWeight"),
    maxWeight: z.number().positive("rates.validationMaxWeight"),
    startDate: z.string().refine(
      (val) => {
        if (!val) return true;
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        const d = new Date(val);
        return d >= today;
      },
      { message: "rates.pastDateError" },
    ),
    endDate: z.string(),
  })
  .refine((data) => data.maxWeight > data.minWeight, {
    message: "rates.validationMaxWeight",
    path: ["maxWeight"],
  })
  .refine(
    (data) => {
      if (data.type === "DEFAULT") return true;
      if (!data.startDate || !data.endDate) return true;
      return new Date(data.startDate) <= new Date(data.endDate);
    },
    {
      message: "rates.validationDateRange",
      path: ["endDate"],
    },
  );

function formatErrorMessage(msg: string): string {
  if (!msg) return "";
  const parts = msg
    .split(/,\s*/)
    .map((p) => p.trim())
    .filter(Boolean);
  const uniqueParts = Array.from(new Set(parts));
  return uniqueParts.join(", ");
}

function mapExistingRateToForm(existingRate: {
  code?: string;
  name?: string;
  type?: string;
  status?: string;
  shippingMethod?: string;
  country?: string;
  origin?: string | null;
  currency?: string;
  weightStep?: unknown;
  minWeight?: unknown;
  maxWeight?: unknown;
  startDate?: Date | string | null;
  endDate?: Date | string | null;
}) {
  return {
    code: existingRate.code ?? "",
    name: existingRate.name ?? "",
    type: (existingRate.type ?? "DEFAULT") as RateCardType,
    status: (existingRate.status ?? "DRAFT") as ContentStatus,
    shippingMethod: (existingRate.shippingMethod ?? "EXPRESS") as ShippingMethod,
    country: existingRate.country ?? "US",
    origin: existingRate.origin ?? "",
    currency: existingRate.currency ?? "USD",
    weightStep: Number(existingRate.weightStep ?? 0.5),
    minWeight: Number(existingRate.minWeight ?? 0.0),
    maxWeight: Number(existingRate.maxWeight ?? 10.0),
    startDate: existingRate.startDate
      ? new Date(existingRate.startDate).toISOString().split("T")[0]
      : "",
    endDate: existingRate.endDate ? new Date(existingRate.endDate).toISOString().split("T")[0] : "",
  };
}

function mapExistingRateToSlabs(existingRate: {
  minWeight?: unknown;
  maxWeight?: unknown;
  items?: {
    startWeight?: unknown;
    endWeight?: unknown;
    rateType?: string;
    amount?: unknown;
  }[];
}): SlabItem[] {
  const minWeight = Number(existingRate.minWeight ?? 0);
  const maxWeight = Number(existingRate.maxWeight ?? 0);

  return (
    existingRate.items?.map((it) => {
      const sw = Number(it.startWeight ?? 0);
      const ew = Number(it.endWeight ?? 0);
      const isAutoGenerated = sw >= minWeight && ew <= maxWeight;

      return {
        startWeight: sw,
        endWeight: ew,
        rateType: (it.rateType ?? "STEP_FIXED") as SlabItem["rateType"],
        amount: Number(it.amount ?? 0),
        isAutoGenerated,
        keyId: `${sw}-${ew}-${Math.random()}`,
      };
    }) ?? []
  );
}

function prepareSavePayload(formData: typeof INITIAL_FORM_STATE) {
  return {
    code: formData.code,
    name: formData.name,
    type: formData.type,
    shippingMethod: formData.shippingMethod,
    country: formData.country,
    origin: formData.origin.trim() === "" ? null : formData.origin.toUpperCase(),
    currency: formData.currency,
    weightStep: formData.weightStep,
    minWeight: formData.minWeight,
    maxWeight: formData.maxWeight,
    startDate: formData.startDate ? new Date(formData.startDate) : null,
    endDate:
      formData.type === "DEFAULT" ? null : formData.endDate ? new Date(formData.endDate) : null,
  };
}

interface StatusBadgeProps {
  status: string;
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string;
}

function StatusBadge({ status, tSettings }: StatusBadgeProps) {
  let variant: "default" | "secondary" | "destructive" | "outline" = "outline";
  let label: string = status;
  if (status === "PUBLISHED") {
    variant = "default";
    label = tSettings("rates.statusPublished");
  } else if (status === "DRAFT") {
    label = tSettings("rates.statusDraft");
  } else if (status === "PENDING") {
    variant = "secondary";
    label = tSettings("rates.statusPending");
  } else if (status === "REJECTED") {
    variant = "destructive";
    label = tSettings("rates.statusRejected");
  } else if (status === "ARCHIVED") {
    variant = "destructive";
    label = tSettings("rates.statusArchived");
  }
  return <Badge variant={variant}>{label}</Badge>;
}

function OverlapWarningBanner({
  cards,
}: {
  cards: Array<{ id?: number; code?: string; startDate?: string; endDate?: string }>;
}) {
  return (
    <div className="flex items-start gap-2.5 p-3 rounded-lg border border-amber-300 bg-amber-50 dark:bg-amber-950/30 text-amber-800 dark:text-amber-300 text-xs">
      <AlertCircle className="size-4 shrink-0 mt-0.5" />
      <div>
        <span className="font-semibold">Cảnh báo chồng chéo thời gian: </span>
        Khoảng thời gian hiệu lực này có nguy cơ xung đột với các bảng giá đang hoạt động:{" "}
        {cards
          .map((c) => c.code ?? "")
          .filter(Boolean)
          .join(", ")}
        .
      </div>
    </div>
  );
}

interface EffectiveDateFieldsProps {
  control: Control<typeof INITIAL_FORM_STATE>;
  errors: FieldErrors<typeof INITIAL_FORM_STATE>;
  type: RateCardType;
  isReadOnly: boolean;
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string;
  getErrorMessage: (field: keyof typeof INITIAL_FORM_STATE) => string | undefined;
}

function EffectiveDateFields({
  control,
  errors,
  type,
  isReadOnly,
  tSettings,
  getErrorMessage,
}: EffectiveDateFieldsProps) {
  const isPastDate = (date: Date) => {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    return date < today;
  };

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
      <div className="flex flex-col gap-1.5">
        <Label className="font-semibold text-xs">{tSettings("rates.lblStartDate")}</Label>
        <Controller
          control={control}
          name="startDate"
          render={({ field }) => (
            <DatePicker
              value={field.value ?? ""}
              onChange={field.onChange}
              placeholder="dd/mm/yyyy"
              disabled={isReadOnly}
              disabledDays={isPastDate}
            />
          )}
        />
        {errors.startDate && (
          <span className="text-[11px] text-destructive font-medium mt-0.5">
            {getErrorMessage("startDate")}
          </span>
        )}
      </div>
      <div className="flex flex-col gap-1.5">
        <Label className="font-semibold text-xs">{tSettings("rates.lblEndDate")}</Label>
        {type === "DEFAULT" ? (
          <div className="h-9 px-3 border border-input rounded-md bg-muted/40 text-xs text-muted-foreground flex items-center">
            {tSettings("rates.defaultEndDateNote")}
          </div>
        ) : (
          <Controller
            control={control}
            name="endDate"
            render={({ field }) => (
              <DatePicker
                value={field.value ?? ""}
                onChange={field.onChange}
                placeholder="dd/mm/yyyy"
                disabled={isReadOnly}
              />
            )}
          />
        )}
        {errors.endDate && (
          <span className="text-[11px] text-destructive font-medium mt-0.5">
            {getErrorMessage("endDate")}
          </span>
        )}
      </div>
    </div>
  );
}

interface GeneralInfoTabProps {
  control: Control<typeof INITIAL_FORM_STATE>;
  register: UseFormRegister<typeof INITIAL_FORM_STATE>;
  errors: FieldErrors<typeof INITIAL_FORM_STATE>;
  watch: UseFormWatch<typeof INITIAL_FORM_STATE>;
  setValue: UseFormSetValue<typeof INITIAL_FORM_STATE>;
  isCreate: boolean;
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string;
  status: ContentStatus;
}

function GeneralInfoTab({
  control,
  register,
  errors,
  watch,
  setValue,
  isCreate,
  tSettings,
  status,
}: GeneralInfoTabProps) {
  const shippingMethod = watch("shippingMethod");
  const type = watch("type");
  const code = watch("code");
  const country = watch("country");
  const origin = watch("origin");
  const startDateStr = watch("startDate");
  const endDateStr = watch("endDate");
  const isDefaultRateCard = ["epacket.default.us", "express.default.us"].includes(code);
  const isReadOnly = !isCreate && status !== "DRAFT" && status !== "REJECTED";

  const getErrorMessage = (field: keyof typeof INITIAL_FORM_STATE) => {
    const err = errors[field];
    if (!err) return undefined;
    return tSettings(err.message as string);
  };

  interface CodeAndNameFieldsProps {
    register: UseFormRegister<typeof INITIAL_FORM_STATE>;
    errors: FieldErrors<typeof INITIAL_FORM_STATE>;
    setValue: UseFormSetValue<typeof INITIAL_FORM_STATE>;
    isDefaultRateCard: boolean;
    isReadOnly: boolean;
    tSettings: (key: string, values?: Record<string, string | number | Date>) => string;
    getErrorMessage: (field: keyof typeof INITIAL_FORM_STATE) => string | undefined;
  }

  function CodeAndNameFields({
    register,
    errors,
    setValue,
    isDefaultRateCard,
    isReadOnly,
    tSettings,
    getErrorMessage,
  }: CodeAndNameFieldsProps) {
    return (
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="flex flex-col gap-1.5">
          <Label htmlFor="code" className="font-semibold text-xs">
            {tSettings("rates.lblCode")} <span className="text-destructive">*</span>
          </Label>
          <Input
            id="code"
            {...register("code")}
            onChange={(e) => {
              setValue("code", e.target.value.toLowerCase(), {
                shouldDirty: true,
                shouldValidate: true,
              });
            }}
            placeholder={tSettings("rates.placeholderCode")}
            disabled={isDefaultRateCard || isReadOnly}
            className={errors.code ? "border-destructive focus-visible:ring-destructive" : ""}
          />
          {errors.code && (
            <span className="text-[11px] text-destructive font-medium mt-0.5">
              {getErrorMessage("code")}
            </span>
          )}
        </div>
        <div className="flex flex-col gap-1.5">
          <Label htmlFor="name" className="font-semibold text-xs">
            {tSettings("rates.lblName")} <span className="text-destructive">*</span>
          </Label>
          <Input
            id="name"
            {...register("name")}
            placeholder={tSettings("rates.placeholderName")}
            disabled={isReadOnly}
            className={errors.name ? "border-destructive focus-visible:ring-destructive" : ""}
          />
          {errors.name && (
            <span className="text-[11px] text-destructive font-medium mt-0.5">
              {getErrorMessage("name")}
            </span>
          )}
        </div>
      </div>
    );
  }

  const { data: overlapRes } = trpc.viewer.rateCards.checkOverlap.useQuery(
    {
      shippingMethod,
      country,
      origin: origin || null,
      startDate: startDateStr ? new Date(startDateStr) : null,
      endDate: endDateStr ? new Date(endDateStr) : null,
    },
    {
      enabled: type === "CUSTOM" && !!shippingMethod && !!country && !!startDateStr,
      staleTime: 10 * 1000,
    },
  );

  return (
    <div className="flex flex-col gap-5">
      {overlapRes?.hasOverlap && <OverlapWarningBanner cards={overlapRes.overlappingCards} />}
      <CodeAndNameFields
        register={register}
        errors={errors}
        setValue={setValue}
        isDefaultRateCard={isDefaultRateCard}
        isReadOnly={isReadOnly}
        tSettings={tSettings}
        getErrorMessage={getErrorMessage}
      />

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div className="flex flex-col gap-1.5">
          <Label className="font-semibold text-xs">
            {tSettings("rates.lblType")} <span className="text-destructive">*</span>
          </Label>
          <Controller
            control={control}
            name="type"
            render={({ field }) => (
              <Select
                value={field.value}
                disabled={isDefaultRateCard || isReadOnly}
                onValueChange={(v) => {
                  field.onChange(v);
                  if (v === "DEFAULT") {
                    setValue("endDate", "", { shouldDirty: true, shouldValidate: true });
                  }
                }}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="DEFAULT">{tSettings("rates.typeDefault")}</SelectItem>
                  <SelectItem value="CUSTOM">{tSettings("rates.typeCustom")}</SelectItem>
                </SelectContent>
              </Select>
            )}
          />
        </div>

        <div className="flex flex-col gap-1.5">
          <Label className="font-semibold text-xs">
            {tSettings("rates.lblShippingMethod")} <span className="text-destructive">*</span>
          </Label>
          <Controller
            control={control}
            name="shippingMethod"
            render={({ field }) => (
              <Select
                value={field.value}
                disabled={isDefaultRateCard || isReadOnly}
                onValueChange={(v) => {
                  field.onChange(v);
                  const defaultStep = v === "EPACKET" ? 0.05 : 0.5;
                  setValue("weightStep", defaultStep, { shouldDirty: true, shouldValidate: true });
                }}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="EXPRESS">Express</SelectItem>
                  <SelectItem value="EPACKET">ePacket</SelectItem>
                </SelectContent>
              </Select>
            )}
          />
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div className="flex flex-col gap-1.5">
          <Label className="font-semibold text-xs">
            {tSettings("rates.lblWeightStep")} <span className="text-destructive">*</span>
          </Label>
          <Controller
            control={control}
            name="weightStep"
            render={({ field }) => (
              <Select
                value={String(field.value)}
                disabled={isDefaultRateCard || isReadOnly}
                onValueChange={(v) => field.onChange(Number(v))}
              >
                <SelectTrigger
                  className={errors.weightStep ? "border-destructive focus:ring-destructive" : ""}
                >
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {shippingMethod === "EPACKET" ? (
                    <>
                      <SelectItem value="0.05">0.05</SelectItem>
                      <SelectItem value="0.1">0.1</SelectItem>
                    </>
                  ) : (
                    <>
                      <SelectItem value="0.5">0.5</SelectItem>
                      <SelectItem value="1">1.0</SelectItem>
                    </>
                  )}
                </SelectContent>
              </Select>
            )}
          />
          {errors.weightStep && (
            <span className="text-[11px] text-destructive font-medium mt-0.5">
              {getErrorMessage("weightStep")}
            </span>
          )}
        </div>
        <div className="flex flex-col gap-1.5">
          <Label className="font-semibold text-xs">
            {tSettings("rates.lblMinWeight")} <span className="text-destructive">*</span>
          </Label>
          <Input
            type="number"
            step={0.01}
            {...register("minWeight", { valueAsNumber: true })}
            disabled={isDefaultRateCard || isReadOnly}
            className={errors.minWeight ? "border-destructive focus-visible:ring-destructive" : ""}
          />
          {errors.minWeight && (
            <span className="text-[11px] text-destructive font-medium mt-0.5">
              {getErrorMessage("minWeight")}
            </span>
          )}
        </div>
        <div className="flex flex-col gap-1.5">
          <Label className="font-semibold text-xs">
            {tSettings("rates.lblMaxWeight")} <span className="text-destructive">*</span>
          </Label>
          <Input
            type="number"
            step={0.01}
            {...register("maxWeight", { valueAsNumber: true })}
            disabled={isDefaultRateCard || isReadOnly}
            className={errors.maxWeight ? "border-destructive focus-visible:ring-destructive" : ""}
          />
        </div>
      </div>

      <EffectiveDateFields
        control={control}
        errors={errors}
        type={type}
        isReadOnly={isReadOnly}
        tSettings={tSettings}
        getErrorMessage={getErrorMessage}
      />
    </div>
  );
}

interface SlabsTabProps {
  formData: {
    code: string;
    currency: string;
    minWeight: number;
    maxWeight: number;
    weightStep: number;
    status: ContentStatus;
  };
  slabs: SlabItem[];
  setSlabs: React.Dispatch<React.SetStateAction<SlabItem[]>>;
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string;
  isReadOnly?: boolean;
}

function getSlabMinCost(slab: SlabItem): number {
  if (slab.rateType === "RANGE_PER_KG") {
    return slab.startWeight * slab.amount;
  }
  return slab.amount;
}

function getSlabMaxCost(slab: SlabItem): number {
  if (slab.rateType === "RANGE_PER_KG") {
    return slab.endWeight * slab.amount;
  }
  return slab.amount;
}

function validateSlabRow(
  curr: SlabItem,
  prev: SlabItem | undefined,
  index: number,
  _totalSlabs: number,
  formData: { minWeight: number; maxWeight: number },
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string,
) {
  if (curr.startWeight >= curr.endWeight) {
    return {
      startWeight: true,
      endWeight: true,
      reason: tSettings("rates.errWeightBounds"),
    };
  }

  const isFirstMinMismatch =
    index === 0 && formData.minWeight != null && curr.startWeight !== formData.minWeight;
  const isGap = prev ? curr.startWeight !== prev.endWeight : false;
  const isMonotonic = prev ? getSlabMinCost(curr) < getSlabMaxCost(prev) : false;

  if (!isFirstMinMismatch && !isGap && !isMonotonic) {
    return {};
  }

  const reason = isFirstMinMismatch
    ? tSettings("rates.errMinWeightMismatch", {
        minWeight: formData.minWeight,
        current: curr.startWeight,
      })
    : isGap
      ? tSettings("rates.errGap", { prevEnd: prev?.endWeight ?? 0 })
      : tSettings("rates.errMonotonicity");

  return {
    startWeight: isFirstMinMismatch || isGap,
    endWeight: false,
    amount: isMonotonic,
    reason,
  };
}

function countSlabErrors(
  slabs: SlabItem[],
  formData: { minWeight: number; maxWeight: number },
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string,
): number {
  let errCount = 0;
  for (let i = 0; i < slabs.length; i++) {
    const err = validateSlabRow(slabs[i], slabs[i - 1], i, slabs.length, formData, tSettings);
    if (err.startWeight || err.endWeight || err.amount) errCount++;
  }
  return errCount;
}

function SlabsTab({ formData, slabs, setSlabs, tSettings, isReadOnly = false }: SlabsTabProps) {
  const t = useToast();
  const templateQuery = trpc.viewer.rateCards.exportSlabsTemplate.useQuery(
    {
      minWeight: formData.minWeight,
      maxWeight: formData.maxWeight,
      weightStep: formData.weightStep,
      rateType: "STEP_FIXED",
    },
    { enabled: false },
  );

  const handleAutoGenerateSlabs = async () => {
    if (isReadOnly) return;
    if (!formData.minWeight && formData.minWeight !== 0) {
      t.toast(tSettings("rates.toastAutoGenerateError"), "error");
      return;
    }
    const res = await templateQuery.refetch();
    if (res.data?.slabs) {
      const generated: SlabItem[] = res.data.slabs.map((s) => ({
        ...s,
        isAutoGenerated: true,
        keyId: `${s.startWeight}-${s.endWeight}-${Math.random()}`,
      }));
      setSlabs(generated);
    }
  };

  const handleDownloadTemplate = () => {
    const csvContent =
      "data:text/csv;charset=utf-8," +
      `${tSettings("rates.csvHeaderStart")},${tSettings("rates.csvHeaderEnd")},${tSettings("rates.csvHeaderType")},${tSettings("rates.csvHeaderAmount")}\n` +
      `0.00,0.50,STEP_FIXED,15.50\n` +
      `0.50,1.00,STEP_FIXED,18.00\n`;
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `RateCard_Slabs_Template_${formData.code || "export"}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleImportCSV = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (isReadOnly) return;
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (evt) => {
      try {
        const text = evt.target?.result as string;
        const imported = parseAndValidateCSVText(text, (line) =>
          tSettings("rates.csvInvalidNumber", { line }),
        );
        setSlabs(imported);

        const errCount = countSlabErrors(imported, formData, tSettings);

        if (errCount > 0) {
          t.toast(
            tSettings("rates.toastImportWithErrors", {
              count: imported.length,
              errorCount: errCount,
            }),
            "warning",
          );
        } else {
          t.toast(tSettings("rates.toastReadCSVSuccess", { count: imported.length }), "success");
        }
      } catch (err) {
        t.toast(
          tSettings("rates.toastErrorCSV", {
            message: err instanceof Error ? err.message : "",
          }),
          "error",
        );
      }
    };
    reader.readAsText(file);
    e.target.value = "";
  };

  const handleAddSlabRow = () => {
    if (isReadOnly) return;
    const last = slabs[slabs.length - 1];
    const start = last ? last.endWeight : formData.minWeight;
    const end = start + (formData.weightStep || 0.5);
    setSlabs((prev) => [
      ...prev,
      {
        startWeight: start,
        endWeight: end,
        rateType: "STEP_FIXED",
        amount: 0.0,
        isAutoGenerated: false,
        keyId: `${start}-${end}-${Math.random()}`,
      },
    ]);
  };

  const handleRemoveSlabRow = (index: number) => {
    if (isReadOnly) return;
    setSlabs((prev) => prev.filter((_, i) => i !== index));
  };

  const updateSlabField = (index: number, field: keyof SlabItem, value: unknown) => {
    if (isReadOnly) return;
    setSlabs((prev) =>
      prev.map((s, i) => {
        if (i === index) {
          return { ...s, [field]: value };
        }
        return s;
      }),
    );
  };

  const slabErrors = useMemo(() => {
    const errMap: Record<
      number,
      { startWeight?: boolean; endWeight?: boolean; amount?: boolean; reason?: string }
    > = {};

    for (let i = 0; i < slabs.length; i++) {
      const err = validateSlabRow(slabs[i], slabs[i - 1], i, slabs.length, formData, tSettings);
      if (err.startWeight || err.endWeight || err.amount) {
        errMap[i] = err;
      }
    }

    return errMap;
  }, [slabs, formData, tSettings]);

  const hasMonotonicityWarning = useMemo(() => {
    return Object.values(slabErrors).some((e) => e.amount);
  }, [slabErrors]);

  return (
    <div className="flex flex-col gap-4">
      {isReadOnly && (
        <div className="bg-blue-50 dark:bg-blue-950/40 border border-blue-200 dark:border-blue-900 rounded-md p-3 text-xs text-blue-800 dark:text-blue-200 flex items-center gap-2">
          <Info className="size-4 shrink-0 text-blue-600 dark:text-blue-400" />
          <span>
            Bảng giá ở trạng thái <strong>{formData.status}</strong> đã được khóa nấc cước để đảm
            bảo tính toàn vẹn dữ liệu tính cước đơn hàng.
          </span>
        </div>
      )}

      {hasMonotonicityWarning && (
        <div className="bg-amber-50 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-900 rounded-md p-3 text-xs text-amber-800 dark:text-amber-200 flex items-start gap-2">
          <AlertCircle className="size-4 shrink-0 text-amber-600 mt-0.5" />
          <div>
            <strong>{tSettings("rates.warningLabel")}</strong>{" "}
            {tSettings("rates.warningMonotonicity")}
          </div>
        </div>
      )}

      <div className="flex flex-wrap items-center justify-between gap-3 bg-muted/20 p-3 rounded-lg border border-border">
        <div className="flex flex-wrap gap-2">
          {!isReadOnly && (
            <Button size="sm" variant="outline" className="h-8" onClick={handleAutoGenerateSlabs}>
              <Wand2 className="mr-1.5 size-3.5" />
              {tSettings("rates.btnAutoGenerate")}
            </Button>
          )}
          <Button size="sm" variant="outline" className="h-8" onClick={handleDownloadTemplate}>
            <Download className="mr-1.5 size-3.5" />
            {tSettings("rates.btnDownloadTemplate")}
          </Button>
        </div>

        {!isReadOnly && (
          <div>
            <label className="cursor-pointer">
              <input type="file" accept=".csv" className="hidden" onChange={handleImportCSV} />
              <Button size="sm" variant="secondary" className="h-8 pointer-events-none">
                <Upload className="mr-1.5 size-3.5" />
                {tSettings("rates.btnImportCSV")}
              </Button>
            </label>
          </div>
        )}
      </div>

      <div className="border border-border rounded-lg overflow-hidden">
        <table className="w-full text-xs text-left">
          <thead className="bg-muted/50 border-b border-border text-muted-foreground font-semibold">
            <tr>
              <th className="px-3 py-2">{tSettings("rates.colStart")}</th>
              <th className="px-3 py-2">{tSettings("rates.colEnd")}</th>
              <th className="px-3 py-2">{tSettings("rates.colSlabType")}</th>
              <th className="px-3 py-2">
                {tSettings("rates.colAmount", { currency: formData.currency })}
              </th>
              {!isReadOnly && (
                <th className="px-3 py-2 text-center w-20 whitespace-nowrap">
                  {tSettings("rates.colDelete")}
                </th>
              )}
            </tr>
          </thead>
          <tbody className="divide-y divide-border">
            {slabs.map((slab, index) => {
              const err = slabErrors[index];
              return (
                <tr
                  key={slab.keyId ?? index}
                  className={cn("hover:bg-muted/20", err && "bg-destructive/5")}
                >
                  <td className="px-3 py-1.5">
                    <Input
                      type="number"
                      step={0.01}
                      value={slab.startWeight}
                      onChange={(e) =>
                        updateSlabField(index, "startWeight", Number(e.target.value))
                      }
                      disabled={isReadOnly || slab.isAutoGenerated}
                      className={cn(
                        "h-7 text-xs px-2",
                        err?.startWeight &&
                          "border-destructive text-destructive bg-destructive/10 focus-visible:ring-destructive font-medium",
                      )}
                    />
                  </td>
                  <td className="px-3 py-1.5">
                    <Input
                      type="number"
                      step={0.01}
                      value={slab.endWeight}
                      onChange={(e) => updateSlabField(index, "endWeight", Number(e.target.value))}
                      disabled={isReadOnly || slab.isAutoGenerated}
                      className={cn(
                        "h-7 text-xs px-2",
                        err?.endWeight &&
                          "border-destructive text-destructive bg-destructive/10 focus-visible:ring-destructive font-medium",
                      )}
                    />
                  </td>
                  <td className="px-3 py-1.5">
                    <Select
                      value={slab.rateType}
                      onValueChange={(v) =>
                        updateSlabField(index, "rateType", v as SlabItem["rateType"])
                      }
                      disabled={isReadOnly || slab.isAutoGenerated}
                    >
                      <SelectTrigger className="h-7 text-xs px-2">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="STEP_FIXED">
                          {tSettings("rates.typeStepFixed")}
                        </SelectItem>
                        <SelectItem value="RANGE_FIXED">
                          {tSettings("rates.typeRangeFixed")}
                        </SelectItem>
                        <SelectItem value="RANGE_PER_KG">
                          {tSettings("rates.typeRangePerKg")}
                        </SelectItem>
                      </SelectContent>
                    </Select>
                  </td>
                  <td className="px-3 py-1.5">
                    <Input
                      type="number"
                      step={0.01}
                      value={slab.amount}
                      onChange={(e) => updateSlabField(index, "amount", Number(e.target.value))}
                      disabled={isReadOnly}
                      className={cn(
                        "h-7 text-xs px-2",
                        err?.amount &&
                          "border-destructive text-destructive bg-destructive/10 focus-visible:ring-destructive font-medium",
                      )}
                    />
                    {err?.reason && (
                      <span className="text-[10px] text-destructive block mt-0.5 font-medium">
                        {err.reason}
                      </span>
                    )}
                  </td>
                  {!isReadOnly && (
                    <td className="px-3 py-1.5 text-center">
                      <Button
                        size="icon"
                        variant="ghost"
                        className="size-7 text-destructive"
                        onClick={() => handleRemoveSlabRow(index)}
                      >
                        <Trash2 className="size-3.5" />
                      </Button>
                    </td>
                  )}
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {!isReadOnly && (
        <Button size="sm" variant="outline" className="w-fit" onClick={handleAddSlabRow}>
          <Plus className="mr-1.5 size-3.5" />
          {tSettings("rates.btnAddSlab")}
        </Button>
      )}
    </div>
  );
}

interface LogsTabProps {
  logs?: {
    id?: number;
    action?: string;
    createdAt?: Date | string;
    userId?: string;
    user?: { name: string; id: string; email: string } | null;
    oldValues?: unknown;
    newValues?: unknown;
  }[];
  loadingLogs: boolean;
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string;
}

function LogsTab({ logs, loadingLogs, tSettings }: LogsTabProps) {
  const tAudit = useTranslations("auditLogs");

  return (
    <div className="flex flex-col gap-4">
      {loadingLogs ? (
        <div className="flex py-12 justify-center items-center">
          <Loader2 className="size-6 animate-spin text-muted-foreground" />
        </div>
      ) : (
        <div className="relative border-l border-border ml-3 pl-5 space-y-4">
          {logs?.map((log, index) => {
            return (
              <div key={log.id ?? index} className="relative group text-xs">
                <div className="absolute -left-[26px] top-0.5 size-3 rounded-full border-2 border-background bg-primary group-hover:scale-110 transition-transform" />

                <div className="flex justify-between text-muted-foreground mb-1">
                  <span className="font-semibold text-foreground">{log.action ?? ""}</span>
                  <span>
                    {log.createdAt ? formatDateTime(log.createdAt, "DD-MM-YYYY HH:mm:ss") : ""}
                  </span>
                </div>

                <div className="bg-muted/40 border border-border/60 rounded-md p-4 space-y-3">
                  <div className="flex items-center gap-1.5 text-[11px] text-muted-foreground border-b border-border/40 pb-2">
                    <Users className="size-3.5" />
                    <span>
                      {tSettings("rates.logPerformedBy")}{" "}
                      <strong className="text-foreground">
                        {log.user?.email || tSettings("rates.logSystem")}
                      </strong>{" "}
                      (ID: {log.userId ?? ""})
                    </span>
                  </div>

                  <VisualDiffViewer
                    action={log.action}
                    oldValues={log.oldValues}
                    newValues={log.newValues}
                    t={tAudit}
                  />
                </div>
              </div>
            );
          })}

          {(!logs || logs.length === 0) && (
            <div className="text-center py-6 text-muted-foreground italic text-xs">
              {tSettings("rates.noLogsFound")}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

interface FormHeaderProps {
  isCreate: boolean;
  code: string;
  status: string;
  activeTab: "info" | "slabs" | "logs";
  isPending: boolean;
  slabsCount: number;
  totalSlabErrors?: number;
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string;
  onBack: () => void;
  onSaveInfo: () => void;
  onSubmitReview?: () => void;
  onApprove?: () => void;
  onReject?: () => void;
  onSaveSlabs: () => void;
  isInfoDirty?: boolean;
  isSlabsDirty?: boolean;
  isReadOnly?: boolean;
}

function InfoTabButtons({
  isCreate,
  status,
  code,
  isPending,
  isInfoDirty,
  totalSlabErrors = 0,
  tSettings,
  onSaveInfo,
  onSubmitReview,
  onApprove,
  onReject,
}: Omit<FormHeaderProps, "activeTab" | "slabsCount" | "onBack" | "onSaveSlabs" | "isSlabsDirty">) {
  return (
    <>
      {(isCreate || status === "DRAFT" || status === "REJECTED") && (
        <Button
          size="sm"
          variant="outline"
          disabled={isPending || !code || (!isCreate && !isInfoDirty)}
          onClick={onSaveInfo}
        >
          {isPending ? (
            <Loader2 className="mr-2 size-4 animate-spin" />
          ) : (
            <Save className="mr-2 size-4" />
          )}
          {isCreate ? tSettings("rates.btnCreate") : tSettings("rates.btnSave")}
        </Button>
      )}

      {!isCreate && (status === "DRAFT" || status === "REJECTED") && onSubmitReview && (
        <Button size="sm" disabled={isPending || totalSlabErrors > 0} onClick={onSubmitReview}>
          <CheckCircle className="mr-2 size-4" />
          {tSettings("rates.btnSubmitReview")}
        </Button>
      )}

      {!isCreate && status === "PENDING" && (
        <>
          {onReject && (
            <Button size="sm" variant="destructive" disabled={isPending} onClick={onReject}>
              {tSettings("rates.btnReject")}
            </Button>
          )}
          {onApprove && (
            <Button size="sm" disabled={isPending || totalSlabErrors > 0} onClick={onApprove}>
              <CheckCircle className="mr-2 size-4" />
              {tSettings("rates.btnApprove")}
            </Button>
          )}
        </>
      )}
    </>
  );
}

function FormHeader(props: FormHeaderProps) {
  const {
    isCreate,
    code,
    status,
    activeTab,
    isPending,
    slabsCount,
    totalSlabErrors = 0,
    tSettings,
    onBack,
    onSaveSlabs,
    isSlabsDirty = false,
    isReadOnly = false,
  } = props;

  return (
    <div className="sticky top-12 md:top-16 z-20 bg-background/95 backdrop-blur-sm py-4 border-b border-border flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 transition-all">
      <div className="flex items-center gap-3">
        <Button variant="ghost" size="icon" className="rounded-full" onClick={onBack}>
          <ChevronLeft className="size-5" />
        </Button>
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-bold tracking-tight text-foreground">
              {isCreate ? tSettings("rates.createTitle") : tSettings("rates.editTitle", { code })}
            </h1>
            {!isCreate && <StatusBadge status={status} tSettings={tSettings} />}
          </div>
          <p className="text-xs text-muted-foreground mt-1">
            {isCreate ? tSettings("rates.createSubtitle") : tSettings("rates.editSubtitle")}
          </p>
        </div>
      </div>

      <div className="flex items-center gap-3">
        <Button variant="outline" size="sm" onClick={onBack}>
          <ArrowLeft className="mr-2 size-4" />
          {tSettings("rates.btnBack")}
        </Button>

        {activeTab === "info" && <InfoTabButtons {...props} />}

        {activeTab === "slabs" && !isCreate && !isReadOnly && (
          <Button
            size="sm"
            disabled={isPending || slabsCount === 0 || !isSlabsDirty || totalSlabErrors > 0}
            onClick={onSaveSlabs}
          >
            {isPending ? (
              <Loader2 className="mr-2 size-4 animate-spin" />
            ) : (
              <CheckCircle className="mr-2 size-4" />
            )}
            {tSettings("rates.btnSaveSlabs")}
          </Button>
        )}
      </div>
    </div>
  );
}

export function RateCardForm({ rateCardId }: RateCardFormProps) {
  const isCreate = rateCardId === null;
  const router = useRouter();
  const t = useToast();
  const tSettings = useTranslations("settings");
  const utils = trpc.useUtils();

  const pathname = usePathname();
  const searchParams = useSearchParams();
  const tabParam = searchParams.get("tab");

  const activeTab = useMemo(() => {
    if (tabParam === "slabs" || tabParam === "logs") return tabParam;
    return "info";
  }, [tabParam]);

  const setActiveTab = useCallback(
    (tab: "info" | "slabs" | "logs") => {
      const params = new URLSearchParams(searchParams.toString());
      params.set("tab", tab);
      const qs = params.toString();
      router.push(`${pathname}${qs ? `?${qs}` : ""}`, { scroll: false });
    },
    [router, pathname, searchParams],
  );

  const {
    register,
    control,
    handleSubmit,
    reset,
    watch,
    setValue,
    formState: { errors, isDirty: isInfoDirty },
  } = useForm<typeof INITIAL_FORM_STATE>({
    resolver: zodResolver(rateCardFormSchema),
    defaultValues: INITIAL_FORM_STATE,
  });

  const formData = watch();
  const [slabs, setSlabs] = useState<SlabItem[]>([]);
  const [initialSlabs, setInitialSlabs] = useState<SlabItem[]>([]);
  const isReadOnly = !isCreate && formData.status !== "DRAFT" && formData.status !== "REJECTED";

  const { data: existingRate, isLoading: loadingDetails } = trpc.viewer.rateCards.get.useQuery(
    { id: rateCardId ?? 0 },
    { enabled: !isCreate && rateCardId !== null },
  );

  const { data: logs, isLoading: loadingLogs } = trpc.viewer.rateCards.listLogs.useQuery(
    { id: rateCardId ?? 0 },
    { enabled: !isCreate && rateCardId !== null && activeTab === "logs" },
  );

  useEffect(() => {
    if (isCreate) {
      reset(INITIAL_FORM_STATE);
      setSlabs([]);
      setInitialSlabs([]);
    } else if (existingRate) {
      const formVal = mapExistingRateToForm(existingRate);
      reset(formVal);
      const slabVal = mapExistingRateToSlabs(existingRate);
      setSlabs(slabVal);
      setInitialSlabs(slabVal);
    }
  }, [isCreate, existingRate, reset]);

  const isSlabsDirty = useMemo(() => {
    if (slabs.length !== initialSlabs.length) return true;
    for (let i = 0; i < slabs.length; i++) {
      const s1 = slabs[i];
      const s2 = initialSlabs[i];
      if (
        s1.startWeight !== s2.startWeight ||
        s1.endWeight !== s2.endWeight ||
        s1.rateType !== s2.rateType ||
        s1.amount !== s2.amount
      ) {
        return true;
      }
    }
    return false;
  }, [slabs, initialSlabs]);

  const createMut = trpc.viewer.rateCards.create.useMutation({
    onSuccess: (card) => {
      t.toast(tSettings("rates.toastCreateSuccess"), "success");
      utils.viewer.rateCards.list.invalidate();
      router.push(`/settings/rates/${card.id}/edit`);
    },
    onError: (err) => t.toast(formatErrorMessage(err.message), "error"),
  });

  const updateMut = trpc.viewer.rateCards.update.useMutation({
    onSuccess: () => {
      t.toast(tSettings("rates.toastUpdateSuccess"), "success");
      utils.viewer.rateCards.list.invalidate();
      utils.viewer.rateCards.get.invalidate({ id: rateCardId ?? 0 });
    },
    onError: (err) => t.toast(formatErrorMessage(err.message), "error"),
  });

  const submitReviewMut = trpc.viewer.rateCards.submitForReview.useMutation({
    onSuccess: () => {
      t.toast(tSettings("rates.toastSubmitSuccess"), "success");
      utils.viewer.rateCards.list.invalidate();
      utils.viewer.rateCards.get.invalidate({ id: rateCardId ?? 0 });
    },
    onError: (err) => t.toast(formatErrorMessage(err.message), "error"),
  });

  const approveMut = trpc.viewer.rateCards.approve.useMutation({
    onSuccess: () => {
      t.toast(tSettings("rates.toastApproveSuccess"), "success");
      utils.viewer.rateCards.list.invalidate();
      utils.viewer.rateCards.get.invalidate({ id: rateCardId ?? 0 });
    },
    onError: (err) => t.toast(formatErrorMessage(err.message), "error"),
  });

  const rejectMut = trpc.viewer.rateCards.reject.useMutation({
    onSuccess: () => {
      t.toast(tSettings("rates.toastRejectSuccess"), "success");
      utils.viewer.rateCards.list.invalidate();
      utils.viewer.rateCards.get.invalidate({ id: rateCardId ?? 0 });
    },
    onError: (err) => t.toast(formatErrorMessage(err.message), "error"),
  });

  const importSlabsMut = trpc.viewer.rateCards.importSlabs.useMutation({
    onSuccess: () => {
      t.toast(tSettings("rates.toastImportSuccess"), "success");
      utils.viewer.rateCards.get.invalidate({ id: rateCardId ?? 0 });
    },
    onError: (err) => t.toast(formatErrorMessage(err.message), "error"),
  });

  const handleSaveInfo = handleSubmit(
    (values) => {
      const payload = prepareSavePayload(values);
      if (isCreate) {
        createMut.mutate(payload);
      } else if (rateCardId) {
        updateMut.mutate({ id: rateCardId, ...payload });
      }
    },
    () => {
      t.toast(tSettings("rates.toastValidationError"), "error");
    },
  );

  const handleSubmitReview = () => {
    if (!rateCardId) return;
    submitReviewMut.mutate({ id: rateCardId });
  };

  const handleApprove = () => {
    if (!rateCardId) return;
    approveMut.mutate({ id: rateCardId });
  };

  const handleReject = () => {
    if (!rateCardId) return;
    rejectMut.mutate({ id: rateCardId });
  };

  const handleSaveSlabs = () => {
    if (!rateCardId) return;
    importSlabsMut.mutate({
      rateCardId,
      slabs,
    });
  };

  const totalSlabErrors = useMemo(() => {
    return countSlabErrors(slabs, formData, tSettings);
  }, [slabs, formData, tSettings]);

  const isPending =
    createMut.isPending ||
    updateMut.isPending ||
    submitReviewMut.isPending ||
    approveMut.isPending ||
    rejectMut.isPending ||
    importSlabsMut.isPending;

  if (loadingDetails) {
    return (
      <div className="flex min-h-[400px] items-center justify-center">
        <Loader2 className="size-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-6 w-full">
      <FormHeader
        isCreate={isCreate}
        code={formData.code}
        status={formData.status}
        activeTab={activeTab}
        isPending={isPending}
        slabsCount={slabs.length}
        totalSlabErrors={totalSlabErrors}
        tSettings={tSettings}
        onBack={() => router.push("/settings/rates")}
        onSaveInfo={handleSaveInfo}
        onSubmitReview={handleSubmitReview}
        onApprove={handleApprove}
        onReject={handleReject}
        onSaveSlabs={handleSaveSlabs}
        isInfoDirty={isInfoDirty}
        isSlabsDirty={isSlabsDirty}
        isReadOnly={isReadOnly}
      />

      <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as "info" | "slabs" | "logs")}>
        <Card className="rounded-lg border border-border bg-card overflow-hidden">
          {!isCreate && (
            <div className="px-6 pt-6 pb-2 flex items-center">
              <TabsList className="inline-flex h-10 items-center justify-start rounded-lg bg-muted p-1 border border-border">
                <TabsTrigger
                  value="info"
                  className="flex items-center gap-1.5 rounded-md px-4 py-1.5 text-xs md:text-sm font-medium text-muted-foreground transition-all hover:bg-background/50 hover:text-foreground data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm"
                >
                  <Info size={16} className="shrink-0" />
                  <span>{tSettings("rates.tabGeneral")}</span>
                </TabsTrigger>
                <TabsTrigger
                  value="slabs"
                  className="flex items-center gap-1.5 rounded-md px-4 py-1.5 text-xs md:text-sm font-medium text-muted-foreground transition-all hover:bg-background/50 hover:text-foreground data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm"
                >
                  <Scale size={16} className="shrink-0" />
                  <span>{tSettings("rates.tabSlabs")}</span>
                  {totalSlabErrors > 0 && (
                    <Badge
                      variant="destructive"
                      className="ml-1 px-1.5 py-0 text-[10px] h-4 leading-none font-semibold"
                    >
                      {totalSlabErrors}
                    </Badge>
                  )}
                </TabsTrigger>
                <TabsTrigger
                  value="logs"
                  className="flex items-center gap-1.5 rounded-md px-4 py-1.5 text-xs md:text-sm font-medium text-muted-foreground transition-all hover:bg-background/50 hover:text-foreground data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm"
                >
                  <History size={16} className="shrink-0" />
                  <span>{tSettings("rates.tabLogs")}</span>
                </TabsTrigger>
              </TabsList>
            </div>
          )}

          <CardContent className="px-6 pb-6 pt-6">
            <TabsContent value="info" className="mt-0 outline-none">
              <GeneralInfoTab
                control={control}
                register={register}
                errors={errors}
                watch={watch}
                setValue={setValue}
                isCreate={isCreate}
                tSettings={tSettings}
                status={formData.status}
              />
            </TabsContent>

            {!isCreate && (
              <>
                <TabsContent value="slabs" className="mt-0 outline-none">
                  <SlabsTab
                    formData={formData}
                    slabs={slabs}
                    setSlabs={setSlabs}
                    tSettings={tSettings}
                    isReadOnly={isReadOnly}
                  />
                </TabsContent>

                <TabsContent value="logs" className="mt-0 outline-none">
                  <LogsTab logs={logs} loadingLogs={loadingLogs} tSettings={tSettings} />
                </TabsContent>
              </>
            )}
          </CardContent>
        </Card>
      </Tabs>
    </div>
  );
}
