"use client";

import { VisualDiffViewer } from "@admin/app/(main)/system/audit-logs/AuditLogsContent";
import { useToast } from "@admin/components/toast-provider";
import { trpc } from "@admin/lib/trpc";
import { formatDateTime } from "@admin/utils/dateFormat";
import type { ContentStatus, ShippingMethod } from "@ecom/prisma";
import { Badge } from "@ecom/ui/components/badge";
import { Button } from "@ecom/ui/components/button";
import { Card, CardContent } from "@ecom/ui/components/card";
import { DatePicker } from "@ecom/ui/components/date-picker";
import { Input } from "@ecom/ui/components/input";
import { Label } from "@ecom/ui/components/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@ecom/ui/components/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@ecom/ui/components/tabs";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  AlertTriangle,
  ArrowLeft,
  CheckCircle,
  ChevronLeft,
  Download,
  History,
  Info,
  Loader2,
  Plus,
  RefreshCw,
  Save,
  Scale,
  Trash2,
  Upload,
  Users,
} from "lucide-react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useTranslations } from "next-intl";
import { useCallback, useEffect, useMemo, useState } from "react";
import type {
  Control,
  FieldErrors,
  UseFormRegister,
  UseFormSetValue,
  UseFormWatch,
} from "react-hook-form";
import { Controller, useForm } from "react-hook-form";
import { z } from "zod";

interface RateCardFormProps {
  rateCardId: number | null;
}

type SlabItem = {
  startWeight: number;
  endWeight: number;
  rateType: "STEP_FIXED" | "RANGE_FIXED" | "RANGE_PER_KG";
  amount: number;
  isAutoGenerated?: boolean;
  keyId: string;
};

// 1. Monotonicity check logic extracted to reduce complexity
function checkSlabsMonotonicity(slabs: SlabItem[]): boolean {
  const sorted = [...slabs].sort((a, b) => a.startWeight - b.startWeight);
  for (let i = 1; i < sorted.length; i++) {
    const prev = sorted[i - 1];
    const curr = sorted[i];
    if (!prev || !curr) continue;

    const costPrevEnd =
      prev.rateType === "RANGE_PER_KG" ? prev.endWeight * prev.amount : prev.amount;
    const costCurrentStart =
      curr.rateType === "RANGE_PER_KG" ? curr.startWeight * curr.amount : curr.amount;

    if (costCurrentStart < costPrevEnd) {
      return false;
    }
  }
  return true;
}

// 2. CSV parsing logic extracted to reduce complexity
function parseSlabsCSV(
  text: string,
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string,
): SlabItem[] {
  const lines = text
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);

  const parsed: SlabItem[] = [];
  for (let i = 1; i < lines.length; i++) {
    const line = lines[i];
    if (!line) continue;
    const parts = line.split(",");
    if (parts.length < 4) continue;
    const startWeight = Number(parts[0]);
    const endWeight = Number(parts[1]);
    const rateType = parts[2] as SlabItem["rateType"];
    const amount = Number(parts[3]);

    if (Number.isNaN(startWeight) || Number.isNaN(endWeight) || Number.isNaN(amount)) {
      throw new Error(tSettings("rates.csvInvalidNumber", { line: i + 1 }));
    }
    parsed.push({
      startWeight,
      endWeight,
      rateType,
      amount,
      keyId: `${startWeight}-${endWeight}-${Math.random()}`,
    });
  }
  return parsed;
}

// 3. Auto generation logic extracted to reduce complexity
function generateSlabItems(minW: number, maxW: number, step: number): SlabItem[] {
  const generated: SlabItem[] = [];
  let current = minW;
  while (current < maxW) {
    const next = Math.min(maxW, Number((current + step).toFixed(3)));
    generated.push({
      startWeight: current,
      endWeight: next,
      rateType: "STEP_FIXED",
      amount: 0.0,
      isAutoGenerated: true,
      keyId: `${current}-${next}-${Math.random()}`,
    });
    current = next;
  }
  return generated;
}

// 4. Add slab calculation logic extracted to reduce complexity
function calculateNewSlabRow(
  slabs: SlabItem[],
  minWeight: number,
  maxWeight: number,
  weightStep: number,
): SlabItem {
  const sorted = [...slabs].sort((a, b) => a.startWeight - b.startWeight);
  const lastSlab = sorted[sorted.length - 1];
  const start = lastSlab ? lastSlab.endWeight : minWeight;
  const step = weightStep || 0.5;
  const end =
    start >= maxWeight
      ? Number((start + step).toFixed(3))
      : Math.min(maxWeight, Number((start + step).toFixed(3)));
  return {
    startWeight: start,
    endWeight: end,
    rateType: lastSlab ? lastSlab.rateType : "STEP_FIXED",
    amount: 0.0,
    keyId: `${start}-${end}-${Math.random()}`,
  };
}

const INITIAL_FORM_STATE = {
  code: "",
  name: "",
  status: "DRAFT" as ContentStatus,
  shippingMethod: "EXPRESS" as ShippingMethod,
  country: "US",
  origin: "",
  currency: "USD",
  weightStep: 0.5,
  minWeight: 0.0,
  maxWeight: 10.0,
  startDate: "",
  endDate: "",
  customerGroupIds: [] as number[],
};

const rateCardFormSchema = z
  .object({
    code: z.string().trim().min(1, "rates.validationRequiredCode"),
    name: z.string().trim().min(1, "rates.validationRequiredName"),
    status: z.custom<ContentStatus>(),
    shippingMethod: z.custom<ShippingMethod>(),
    country: z.string(),
    origin: z.string(),
    currency: z.string(),
    weightStep: z.number().positive("rates.validationWeightStep"),
    minWeight: z.number().nonnegative("rates.validationMinWeight"),
    maxWeight: z.number().positive("rates.validationMaxWeight"),
    startDate: z.string(),
    endDate: z.string(),
    customerGroupIds: z.array(z.number()),
  })
  .refine((data) => data.maxWeight > data.minWeight, {
    message: "rates.validationMaxWeight",
    path: ["maxWeight"],
  })
  .refine(
    (data) => {
      if (!data.startDate || !data.endDate) return true;
      return new Date(data.startDate) <= new Date(data.endDate);
    },
    {
      message: "rates.validationDateRange",
      path: ["endDate"],
    },
  );

function formatErrorMessage(msg: string): string {
  if (!msg) return "";
  const parts = msg
    .split(/,\s*/)
    .map((p) => p.trim())
    .filter(Boolean);
  const uniqueParts = Array.from(new Set(parts));
  return uniqueParts.join(", ");
}

function mapExistingRateToForm(existingRate: {
  code?: string;
  name?: string;
  status?: string;
  shippingMethod?: string;
  country?: string;
  origin?: string | null;
  currency?: string;
  weightStep?: unknown;
  minWeight?: unknown;
  maxWeight?: unknown;
  startDate?: Date | string | null;
  endDate?: Date | string | null;
  groups?: { customerGroupId: number }[];
}) {
  return {
    code: existingRate.code ?? "",
    name: existingRate.name ?? "",
    status: (existingRate.status ?? "DRAFT") as ContentStatus,
    shippingMethod: (existingRate.shippingMethod ?? "EXPRESS") as ShippingMethod,
    country: existingRate.country ?? "US",
    origin: existingRate.origin ?? "",
    currency: existingRate.currency ?? "USD",
    weightStep: Number(existingRate.weightStep ?? 0.5),
    minWeight: Number(existingRate.minWeight ?? 0.0),
    maxWeight: Number(existingRate.maxWeight ?? 10.0),
    startDate: existingRate.startDate
      ? new Date(existingRate.startDate).toISOString().split("T")[0]
      : "",
    endDate: existingRate.endDate ? new Date(existingRate.endDate).toISOString().split("T")[0] : "",
    customerGroupIds: existingRate.groups?.map((cg) => cg.customerGroupId) ?? [],
  };
}

function mapExistingRateToSlabs(existingRate: {
  minWeight?: unknown;
  maxWeight?: unknown;
  items?: {
    startWeight?: unknown;
    endWeight?: unknown;
    rateType?: string;
    amount?: unknown;
  }[];
}): SlabItem[] {
  const minWeight = Number(existingRate.minWeight ?? 0);
  const maxWeight = Number(existingRate.maxWeight ?? 0);

  return (
    existingRate.items?.map((it) => {
      const sw = Number(it.startWeight ?? 0);
      const ew = Number(it.endWeight ?? 0);
      const isAutoGenerated = sw >= minWeight && ew <= maxWeight;

      return {
        startWeight: sw,
        endWeight: ew,
        rateType: (it.rateType ?? "STEP_FIXED") as SlabItem["rateType"],
        amount: Number(it.amount ?? 0),
        isAutoGenerated,
        keyId: `${sw}-${ew}-${Math.random()}`,
      };
    }) ?? []
  );
}

function prepareSavePayload(formData: typeof INITIAL_FORM_STATE) {
  return {
    ...formData,
    origin: formData.origin.trim() === "" ? null : formData.origin.toUpperCase(),
    startDate: formData.startDate ? new Date(formData.startDate) : null,
    endDate: formData.endDate ? new Date(formData.endDate) : null,
  };
}

// 5. StatusBadge component extracted to reduce complexity
interface StatusBadgeProps {
  status: string;
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string;
}

function StatusBadge({ status, tSettings }: StatusBadgeProps) {
  let variant: "default" | "secondary" | "destructive" | "outline" = "outline";
  let label: string = status;
  if (status === "PUBLISHED") {
    variant = "default";
    label = tSettings("rates.statusPublished");
  } else if (status === "DRAFT") {
    label = tSettings("rates.statusDraft");
  } else if (status === "ARCHIVED") {
    variant = "destructive";
    label = tSettings("rates.statusArchived");
  }
  return <Badge variant={variant}>{label}</Badge>;
}

interface GeneralInfoTabProps {
  control: Control<typeof INITIAL_FORM_STATE>;
  register: UseFormRegister<typeof INITIAL_FORM_STATE>;
  errors: FieldErrors<typeof INITIAL_FORM_STATE>;
  watch: UseFormWatch<typeof INITIAL_FORM_STATE>;
  setValue: UseFormSetValue<typeof INITIAL_FORM_STATE>;
  isCreate: boolean;
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string;
  customerGroups?: { id: number; code: string; name: string }[];
  status: ContentStatus;
}

function GeneralInfoTab({
  control,
  register,
  errors,
  watch,
  setValue,
  isCreate,
  tSettings,
  customerGroups,
  status,
}: GeneralInfoTabProps) {
  const shippingMethod = watch("shippingMethod");
  const customerGroupIds = watch("customerGroupIds");
  const code = watch("code");
  const isDefaultRateCard = ["epacket.default.us", "express.default.us"].includes(code);

  const getErrorMessage = (field: keyof typeof INITIAL_FORM_STATE) => {
    const err = errors[field];
    if (!err) return undefined;
    return tSettings(err.message as string);
  };

  return (
    <div className="flex flex-col gap-5">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="flex flex-col gap-1.5">
          <Label htmlFor="code" className="font-semibold text-xs">
            {tSettings("rates.lblCode")} <span className="text-destructive">*</span>
          </Label>
          <Input
            id="code"
            {...register("code")}
            onChange={(e) => {
              setValue("code", e.target.value.toLowerCase(), {
                shouldDirty: true,
                shouldValidate: true,
              });
            }}
            placeholder={tSettings("rates.placeholderCode")}
            disabled={isDefaultRateCard || (!isCreate && status !== "DRAFT")}
            className={errors.code ? "border-destructive focus-visible:ring-destructive" : ""}
          />
          {errors.code && (
            <span className="text-[11px] text-destructive font-medium mt-0.5">
              {getErrorMessage("code")}
            </span>
          )}
        </div>
        <div className="flex flex-col gap-1.5">
          <Label htmlFor="name" className="font-semibold text-xs">
            {tSettings("rates.lblName")} <span className="text-destructive">*</span>
          </Label>
          <Input
            id="name"
            {...register("name")}
            placeholder={tSettings("rates.placeholderName")}
            className={errors.name ? "border-destructive focus-visible:ring-destructive" : ""}
          />
          {errors.name && (
            <span className="text-[11px] text-destructive font-medium mt-0.5">
              {getErrorMessage("name")}
            </span>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div className="flex flex-col gap-1.5">
          <Label className="font-semibold text-xs">
            {tSettings("rates.lblShippingMethod")} <span className="text-destructive">*</span>
          </Label>
          <Controller
            control={control}
            name="shippingMethod"
            render={({ field }) => (
              <Select
                value={field.value}
                disabled={isDefaultRateCard}
                onValueChange={(v) => {
                  field.onChange(v);
                  const defaultStep = v === "EPACKET" ? 0.05 : 0.5;
                  setValue("weightStep", defaultStep, { shouldDirty: true, shouldValidate: true });
                }}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="EXPRESS">Express</SelectItem>
                  <SelectItem value="EPACKET">ePacket</SelectItem>
                </SelectContent>
              </Select>
            )}
          />
        </div>
        <div className="flex flex-col gap-1.5">
          <Label className="font-semibold text-xs">{tSettings("rates.lblStatus")}</Label>
          <Controller
            control={control}
            name="status"
            render={({ field }) => (
              <Select
                value={field.value}
                disabled={isDefaultRateCard}
                onValueChange={field.onChange}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="DRAFT">{tSettings("rates.statusDraft")}</SelectItem>
                  <SelectItem value="PUBLISHED">{tSettings("rates.statusPublished")}</SelectItem>
                  <SelectItem value="ARCHIVED">{tSettings("rates.statusArchived")}</SelectItem>
                </SelectContent>
              </Select>
            )}
          />
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div className="flex flex-col gap-1.5">
          <Label className="font-semibold text-xs">
            {tSettings("rates.lblWeightStep")} <span className="text-destructive">*</span>
          </Label>
          <Controller
            control={control}
            name="weightStep"
            render={({ field }) => (
              <Select
                value={String(field.value)}
                disabled={isDefaultRateCard}
                onValueChange={(v) => field.onChange(Number(v))}
              >
                <SelectTrigger
                  className={errors.weightStep ? "border-destructive focus:ring-destructive" : ""}
                >
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {shippingMethod === "EPACKET" ? (
                    <>
                      <SelectItem value="0.05">0.05</SelectItem>
                      <SelectItem value="0.1">0.1</SelectItem>
                    </>
                  ) : (
                    <>
                      <SelectItem value="0.5">0.5</SelectItem>
                      <SelectItem value="1">1.0</SelectItem>
                    </>
                  )}
                </SelectContent>
              </Select>
            )}
          />
          {errors.weightStep && (
            <span className="text-[11px] text-destructive font-medium mt-0.5">
              {getErrorMessage("weightStep")}
            </span>
          )}
        </div>
        <div className="flex flex-col gap-1.5">
          <Label className="font-semibold text-xs">
            {tSettings("rates.lblMinWeight")} <span className="text-destructive">*</span>
          </Label>
          <Input
            type="number"
            step={0.01}
            {...register("minWeight", { valueAsNumber: true })}
            disabled={isDefaultRateCard}
            className={errors.minWeight ? "border-destructive focus-visible:ring-destructive" : ""}
          />
          {errors.minWeight && (
            <span className="text-[11px] text-destructive font-medium mt-0.5">
              {getErrorMessage("minWeight")}
            </span>
          )}
        </div>
        <div className="flex flex-col gap-1.5">
          <Label className="font-semibold text-xs">
            {tSettings("rates.lblMaxWeight")} <span className="text-destructive">*</span>
          </Label>
          <Input
            type="number"
            step={0.01}
            {...register("maxWeight", { valueAsNumber: true })}
            disabled={isDefaultRateCard}
            className={errors.maxWeight ? "border-destructive focus-visible:ring-destructive" : ""}
          />
          {errors.maxWeight && (
            <span className="text-[11px] text-destructive font-medium mt-0.5">
              {getErrorMessage("maxWeight")}
            </span>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div className="flex flex-col gap-1.5">
          <Label className="font-semibold text-xs">{tSettings("rates.lblStartDate")}</Label>
          <Controller
            control={control}
            name="startDate"
            render={({ field }) => (
              <DatePicker
                value={field.value ?? ""}
                onChange={field.onChange}
                placeholder="dd/mm/yyyy"
                disabled={isDefaultRateCard}
              />
            )}
          />
        </div>
        <div className="flex flex-col gap-1.5">
          <Label className="font-semibold text-xs">{tSettings("rates.lblEndDate")}</Label>
          <Controller
            control={control}
            name="endDate"
            render={({ field }) => (
              <DatePicker
                value={field.value ?? ""}
                onChange={field.onChange}
                placeholder="dd/mm/yyyy"
                disabled={isDefaultRateCard}
              />
            )}
          />
          {errors.endDate && (
            <span className="text-[11px] text-destructive font-medium mt-0.5">
              {getErrorMessage("endDate")}
            </span>
          )}
        </div>
      </div>

      {/* Multi-select for customer groups */}
      <div className="flex flex-col gap-1.5">
        <Label className="font-semibold text-xs">{tSettings("rates.lblCustomerGroups")}</Label>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 border border-input rounded-md p-3 max-h-36 overflow-y-auto bg-muted/10">
          {customerGroups?.map((group) => {
            const checked = customerGroupIds.includes(group.id);
            return (
              <label
                key={group.id}
                className="flex items-center gap-2 text-sm cursor-pointer select-none"
              >
                <input
                  type="checkbox"
                  checked={checked}
                  disabled={isDefaultRateCard}
                  onChange={() => {
                    const next = checked
                      ? customerGroupIds.filter((id) => id !== group.id)
                      : [...customerGroupIds, group.id];
                    setValue("customerGroupIds", next, { shouldDirty: true, shouldValidate: true });
                  }}
                  className="rounded border-input text-primary focus:ring-primary size-4"
                />
                <span>
                  {group.name} ({group.code})
                </span>
              </label>
            );
          })}
          {(!customerGroups || customerGroups.length === 0) && (
            <span className="text-xs text-muted-foreground italic col-span-2">
              {tSettings("rates.noGroupsFound")}
            </span>
          )}
        </div>
        <p className="text-[11px] text-muted-foreground">
          {tSettings("rates.customerGroupsHelper")}
        </p>
      </div>
    </div>
  );
}

interface SlabsTabProps {
  formData: {
    code: string;
    currency: string;
    minWeight: number;
    maxWeight: number;
    weightStep: number;
  };
  slabs: SlabItem[];
  setSlabs: React.Dispatch<React.SetStateAction<SlabItem[]>>;
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string;
}

function SlabsTab({ formData, slabs, setSlabs, tSettings }: SlabsTabProps) {
  const t = useToast();

  // Generate template slabs automatically based on weight step
  const handleAutoGenerateSlabs = () => {
    const minW = Number(formData.minWeight);
    const maxW = Number(formData.maxWeight);
    const step = Number(formData.weightStep);

    if (maxW <= minW || step <= 0) {
      t.toast(tSettings("rates.toastAutoGenerateError"), "error");
      return;
    }

    setSlabs(generateSlabItems(minW, maxW, step));
  };

  const handleAddSlabRow = () => {
    const minW = Number(formData.minWeight);
    const maxW = Number(formData.maxWeight);
    const step = Number(formData.weightStep);
    setSlabs([...slabs, calculateNewSlabRow(slabs, minW, maxW, step)]);
  };

  const handleRemoveSlabRow = (index: number) => {
    const next = [...slabs];
    next.splice(index, 1);
    setSlabs(next);
  };

  const updateSlabField = <K extends keyof SlabItem>(index: number, field: K, val: SlabItem[K]) => {
    const next = [...slabs];
    const item = next[index];
    if (item) {
      next[index] = {
        ...item,
        [field]: val,
      };
      setSlabs(next);
    }
  };

  // Monotonicity checker
  const isMonotonic = useMemo(() => checkSlabsMonotonicity(slabs), [slabs]);

  // Export CSV
  const handleExportCSV = () => {
    const headers = `${tSettings("rates.csvHeaderStart")},${tSettings("rates.csvHeaderEnd")},${tSettings("rates.csvHeaderType")},${tSettings("rates.csvHeaderAmount")}\n`;
    const rowsText = slabs
      .map((s) => `${s.startWeight},${s.endWeight},${s.rateType},${s.amount}`)
      .join("\n");
    const blob = new Blob([headers + rowsText], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download", `template-nac-cuoc-${formData.code || "rate-card"}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Import CSV
  const handleImportCSV = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (evt) => {
      try {
        const text = evt.target?.result as string;
        const parsed = parseSlabsCSV(text, tSettings);
        setSlabs(parsed);
        t.toast(tSettings("rates.toastReadCSVSuccess", { count: parsed.length }), "success");
      } catch (err) {
        const errMsg = err instanceof Error ? err.message : String(err);
        t.toast(tSettings("rates.toastErrorCSV", { message: errMsg }), "error");
      }
    };
    reader.readAsText(file);
    e.target.value = "";
  };

  return (
    <div className="flex flex-col gap-5">
      {/* Monotonicity Warning Banner */}
      {!isMonotonic && (
        <div className="flex gap-2 rounded-md border border-amber-300 bg-amber-50 dark:bg-amber-950/20 p-3 text-xs text-amber-800 dark:text-amber-300">
          <AlertTriangle className="size-4 shrink-0 mt-0.5" />
          <div>
            <span className="font-semibold">{tSettings("rates.warningLabel")}</span>{" "}
            {tSettings("rates.warningMonotonicity")}
          </div>
        </div>
      )}

      {/* Utility Tools row */}
      <div className="flex flex-wrap gap-2 justify-between items-center bg-muted/30 p-3 rounded-lg border border-border">
        <div className="flex gap-1.5">
          <Button size="sm" variant="outline" className="h-8" onClick={handleAutoGenerateSlabs}>
            <RefreshCw className="mr-1.5 size-3" />
            {tSettings("rates.btnAutoGenerate")}
          </Button>
          <Button size="sm" variant="outline" className="h-8" onClick={handleExportCSV}>
            <Download className="mr-1.5 size-3" />
            {tSettings("rates.btnDownloadTemplate")}
          </Button>
        </div>

        <div className="relative">
          <input
            type="file"
            accept=".csv"
            onChange={handleImportCSV}
            className="absolute inset-0 opacity-0 cursor-pointer w-full h-full"
            id="csv-file-input"
          />
          <Button size="sm" variant="outline" className="h-8">
            <Upload className="mr-1.5 size-3" />
            {tSettings("rates.btnImportCSV")}
          </Button>
        </div>
      </div>

      {/* Slabs Grid Table */}
      <div className="border border-border rounded-lg overflow-hidden bg-card">
        <table className="w-full text-left border-collapse text-xs">
          <thead>
            <tr className="bg-muted/40 border-b border-border">
              <th className="px-3 py-2 font-semibold text-muted-foreground w-28 text-center">
                {tSettings("rates.colStart")}
              </th>
              <th className="px-3 py-2 font-semibold text-muted-foreground w-28 text-center">
                {tSettings("rates.colEnd")}
              </th>
              <th className="px-3 py-2 font-semibold text-muted-foreground w-64">
                {tSettings("rates.colType")}
              </th>
              <th className="px-3 py-2 font-semibold text-muted-foreground">
                {tSettings("rates.colAmount", { currency: formData.currency })}
              </th>
              <th
                className="px-3 py-2 text-center w-12"
                aria-label={tSettings("rates.colDelete")}
              />
            </tr>
          </thead>
          <tbody>
            {slabs.map((slab, index) => (
              <tr
                key={slab.keyId}
                className="border-b border-border last:border-0 hover:bg-muted/10"
              >
                <td className="px-3 py-1.5 w-28">
                  <Input
                    type="number"
                    step={formData.weightStep || 0.1}
                    value={slab.startWeight}
                    onChange={(e) => updateSlabField(index, "startWeight", Number(e.target.value))}
                    className="h-7 text-xs px-2 text-center"
                    disabled={slab.isAutoGenerated}
                  />
                </td>
                <td className="px-3 py-1.5 w-28">
                  <Input
                    type="number"
                    step={formData.weightStep || 0.1}
                    value={slab.endWeight}
                    onChange={(e) => updateSlabField(index, "endWeight", Number(e.target.value))}
                    className="h-7 text-xs px-2 text-center"
                    disabled={slab.isAutoGenerated}
                  />
                </td>
                <td className="px-3 py-1.5 w-64">
                  <Select
                    value={slab.rateType}
                    onValueChange={(v) =>
                      updateSlabField(index, "rateType", v as SlabItem["rateType"])
                    }
                    disabled={slab.isAutoGenerated}
                  >
                    <SelectTrigger className="h-7 text-xs px-2">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="STEP_FIXED">{tSettings("rates.typeStepFixed")}</SelectItem>
                      <SelectItem value="RANGE_FIXED">
                        {tSettings("rates.typeRangeFixed")}
                      </SelectItem>
                      <SelectItem value="RANGE_PER_KG">
                        {tSettings("rates.typeRangePerKg")}
                      </SelectItem>
                    </SelectContent>
                  </Select>
                </td>
                <td className="px-3 py-1.5">
                  <Input
                    type="number"
                    step={0.01}
                    value={slab.amount}
                    onChange={(e) => updateSlabField(index, "amount", Number(e.target.value))}
                    className="h-7 text-xs px-2 font-medium"
                  />
                </td>
                <td className="px-3 py-1.5 text-center">
                  {!slab.isAutoGenerated && (
                    <button
                      type="button"
                      onClick={() => handleRemoveSlabRow(index)}
                      className="text-destructive hover:bg-red-50 p-1 rounded-md transition-colors"
                    >
                      <Trash2 size={14} />
                    </button>
                  )}
                </td>
              </tr>
            ))}
            {slabs.length === 0 && (
              <tr>
                <td
                  colSpan={5}
                  className="py-8 text-center text-muted-foreground italic bg-muted/5"
                >
                  {tSettings("rates.noSlabs")}
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      <div className="flex gap-2">
        <Button size="sm" variant="outline" className="h-8 w-fit" onClick={handleAddSlabRow}>
          <Plus className="mr-1.5 size-3" />
          {tSettings("rates.btnAddSlab")}
        </Button>
      </div>
    </div>
  );
}

interface LogsTabProps {
  logs?: {
    id?: number;
    action?: string;
    createdAt?: Date | string;
    userId?: number;
    user?: { email: string } | null;
    oldValues?: unknown;
    newValues?: unknown;
  }[];
  loadingLogs: boolean;
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string;
}

function LogsTab({ logs, loadingLogs, tSettings }: LogsTabProps) {
  const tAudit = useTranslations("auditLogs");

  return (
    <div className="flex flex-col gap-4">
      <span className="text-xs font-semibold text-muted-foreground">
        {tSettings("rates.logTitle")}
      </span>

      {loadingLogs ? (
        <div className="flex py-12 justify-center items-center">
          <Loader2 className="size-6 animate-spin text-muted-foreground" />
        </div>
      ) : (
        <div className="relative border-l border-border ml-3 pl-5 space-y-4">
          {logs?.map((log, index) => {
            return (
              <div key={log.id ?? index} className="relative group text-xs">
                <div className="absolute -left-[26px] top-0.5 size-3 rounded-full border-2 border-background bg-primary group-hover:scale-110 transition-transform" />

                <div className="flex justify-between text-muted-foreground mb-1">
                  <span className="font-semibold text-foreground">{log.action ?? ""}</span>
                  <span>
                    {log.createdAt ? formatDateTime(log.createdAt, "DD-MM-YYYY HH:mm:ss") : ""}
                  </span>
                </div>

                <div className="bg-muted/40 border border-border/60 rounded-md p-4 space-y-3">
                  <div className="flex items-center gap-1.5 text-[11px] text-muted-foreground border-b border-border/40 pb-2">
                    <Users className="size-3.5" />
                    <span>
                      {tSettings("rates.logPerformedBy")}{" "}
                      <strong className="text-foreground">
                        {log.user?.email || tSettings("rates.logSystem")}
                      </strong>{" "}
                      (ID: {log.userId ?? ""})
                    </span>
                  </div>

                  <VisualDiffViewer
                    action={log.action}
                    oldValues={log.oldValues}
                    newValues={log.newValues}
                    t={tAudit}
                  />
                </div>
              </div>
            );
          })}

          {(!logs || logs.length === 0) && (
            <div className="text-center py-6 text-muted-foreground italic text-xs">
              {tSettings("rates.noLogsFound")}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

interface FormHeaderProps {
  isCreate: boolean;
  code: string;
  status: string;
  activeTab: "info" | "slabs" | "logs";
  isPending: boolean;
  slabsCount: number;
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string;
  onBack: () => void;
  onSaveInfo: () => void;
  onSaveSlabs: () => void;
  isInfoDirty?: boolean;
  isSlabsDirty?: boolean;
}

function FormHeader({
  isCreate,
  code,
  status,
  activeTab,
  isPending,
  slabsCount,
  tSettings,
  onBack,
  onSaveInfo,
  onSaveSlabs,
  isInfoDirty = false,
  isSlabsDirty = false,
}: FormHeaderProps) {
  return (
    <div className="sticky top-12 md:top-16 z-20 bg-background/95 backdrop-blur-sm py-4 border-b border-border flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 transition-all">
      <div className="flex items-center gap-3">
        <Button variant="ghost" size="icon" className="rounded-full" onClick={onBack}>
          <ChevronLeft className="size-5" />
        </Button>
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-bold tracking-tight text-foreground">
              {isCreate ? tSettings("rates.createTitle") : tSettings("rates.editTitle", { code })}
            </h1>
            {!isCreate && <StatusBadge status={status} tSettings={tSettings} />}
          </div>
          <p className="text-xs text-muted-foreground mt-1">
            {isCreate ? tSettings("rates.createSubtitle") : tSettings("rates.editSubtitle")}
          </p>
        </div>
      </div>

      <div className="flex items-center gap-3">
        <Button variant="outline" size="sm" onClick={onBack}>
          <ArrowLeft className="mr-2 size-4" />
          {tSettings("rates.btnBack")}
        </Button>
        {activeTab === "info" && (
          <Button
            size="sm"
            disabled={isPending || !code || (!isCreate && !isInfoDirty)}
            onClick={onSaveInfo}
          >
            {isPending ? (
              <Loader2 className="mr-2 size-4 animate-spin" />
            ) : (
              <Save className="mr-2 size-4" />
            )}
            {isCreate ? tSettings("rates.btnCreate") : tSettings("rates.btnSave")}
          </Button>
        )}
        {activeTab === "slabs" && !isCreate && (
          <Button
            size="sm"
            disabled={isPending || slabsCount === 0 || !isSlabsDirty}
            onClick={onSaveSlabs}
          >
            {isPending ? (
              <Loader2 className="mr-2 size-4 animate-spin" />
            ) : (
              <CheckCircle className="mr-2 size-4" />
            )}
            {tSettings("rates.btnSaveSlabs")}
          </Button>
        )}
      </div>
    </div>
  );
}

export function RateCardForm({ rateCardId }: RateCardFormProps) {
  const isCreate = rateCardId === null;
  const router = useRouter();
  const t = useToast();
  const tSettings = useTranslations("settings");
  const utils = trpc.useUtils();

  const pathname = usePathname();
  const searchParams = useSearchParams();
  const tabParam = searchParams.get("tab");

  const activeTab = useMemo(() => {
    if (tabParam === "slabs" || tabParam === "logs") return tabParam;
    return "info";
  }, [tabParam]);

  const setActiveTab = useCallback(
    (tab: "info" | "slabs" | "logs") => {
      const params = new URLSearchParams(searchParams.toString());
      params.set("tab", tab);
      const qs = params.toString();
      router.push(`${pathname}${qs ? `?${qs}` : ""}`, { scroll: false });
    },
    [router, pathname, searchParams],
  );

  // Form State
  const {
    register,
    control,
    handleSubmit,
    reset,
    watch,
    setValue,
    formState: { errors, isDirty: isInfoDirty },
  } = useForm<typeof INITIAL_FORM_STATE>({
    resolver: zodResolver(rateCardFormSchema),
    defaultValues: INITIAL_FORM_STATE,
  });

  const formData = watch();

  // Local slabs state
  const [slabs, setSlabs] = useState<SlabItem[]>([]);
  const [initialSlabs, setInitialSlabs] = useState<SlabItem[]>([]);

  // Query groups helper
  const { data: customerGroups } = trpc.viewer.rateCards.listGroups.useQuery();

  // Query rate details
  const { data: existingRate, isLoading: loadingDetails } = trpc.viewer.rateCards.get.useQuery(
    { id: rateCardId ?? 0 },
    { enabled: !isCreate && rateCardId !== null },
  );

  // Query audit logs
  const { data: logs, isLoading: loadingLogs } = trpc.viewer.rateCards.listLogs.useQuery(
    { id: rateCardId ?? 0 },
    { enabled: !isCreate && rateCardId !== null && activeTab === "logs" },
  );

  // Reset/populate form when query loads or creates
  useEffect(() => {
    if (isCreate) {
      reset(INITIAL_FORM_STATE);
      setSlabs([]);
      setInitialSlabs([]);
    } else if (existingRate) {
      const formVal = mapExistingRateToForm(existingRate);
      reset(formVal);
      const slabVal = mapExistingRateToSlabs(existingRate);
      setSlabs(slabVal);
      setInitialSlabs(slabVal);
    }
  }, [isCreate, existingRate, reset]);

  const isSlabsDirty = useMemo(() => {
    if (slabs.length !== initialSlabs.length) return true;
    for (let i = 0; i < slabs.length; i++) {
      const s1 = slabs[i];
      const s2 = initialSlabs[i];
      if (
        s1.startWeight !== s2.startWeight ||
        s1.endWeight !== s2.endWeight ||
        s1.rateType !== s2.rateType ||
        s1.amount !== s2.amount
      ) {
        return true;
      }
    }
    return false;
  }, [slabs, initialSlabs]);

  // Mutations
  const createMut = trpc.viewer.rateCards.create.useMutation({
    onSuccess: (card) => {
      t.toast(tSettings("rates.toastCreateSuccess"), "success");
      utils.viewer.rateCards.list.invalidate();
      router.push(`/settings/rates/${card.id}/edit`);
    },
    onError: (err) => t.toast(formatErrorMessage(err.message), "error"),
  });

  const updateMut = trpc.viewer.rateCards.update.useMutation({
    onSuccess: () => {
      t.toast(tSettings("rates.toastUpdateSuccess"), "success");
      utils.viewer.rateCards.list.invalidate();
      utils.viewer.rateCards.get.invalidate({ id: rateCardId ?? 0 });
    },
    onError: (err) => t.toast(formatErrorMessage(err.message), "error"),
  });

  const importSlabsMut = trpc.viewer.rateCards.importSlabs.useMutation({
    onSuccess: () => {
      t.toast(tSettings("rates.toastImportSuccess"), "success");
      utils.viewer.rateCards.get.invalidate({ id: rateCardId ?? 0 });
    },
    onError: (err) => t.toast(formatErrorMessage(err.message), "error"),
  });

  const handleSaveInfo = handleSubmit(
    (values) => {
      const payload = prepareSavePayload(values);
      if (isCreate) {
        createMut.mutate(payload);
      } else if (rateCardId) {
        updateMut.mutate({ id: rateCardId, ...payload });
      }
    },
    () => {
      t.toast(tSettings("rates.toastValidationError"), "error");
    },
  );

  const handleSaveSlabs = () => {
    if (!rateCardId) return;
    importSlabsMut.mutate({
      rateCardId,
      slabs,
    });
  };

  const isPending = createMut.isPending || updateMut.isPending || importSlabsMut.isPending;

  if (loadingDetails) {
    return (
      <div className="flex min-h-[400px] items-center justify-center">
        <Loader2 className="size-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-6 w-full">
      <FormHeader
        isCreate={isCreate}
        code={formData.code}
        status={formData.status}
        activeTab={activeTab}
        isPending={isPending}
        slabsCount={slabs.length}
        tSettings={tSettings}
        onBack={() => router.push("/settings/rates")}
        onSaveInfo={handleSaveInfo}
        onSaveSlabs={handleSaveSlabs}
        isInfoDirty={isInfoDirty}
        isSlabsDirty={isSlabsDirty}
      />

      <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as "info" | "slabs" | "logs")}>
        <Card className="rounded-lg border border-border bg-card overflow-hidden">
          {!isCreate && (
            <div className="px-6 pt-6 pb-2 flex items-center">
              <TabsList className="inline-flex h-10 items-center justify-start rounded-lg bg-muted p-1 border border-border">
                <TabsTrigger
                  value="info"
                  className="flex items-center gap-1.5 rounded-md px-4 py-1.5 text-xs md:text-sm font-medium text-muted-foreground transition-all hover:bg-background/50 hover:text-foreground data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm"
                >
                  <Info size={16} className="shrink-0" />
                  <span>{tSettings("rates.tabGeneral")}</span>
                </TabsTrigger>
                <TabsTrigger
                  value="slabs"
                  className="flex items-center gap-1.5 rounded-md px-4 py-1.5 text-xs md:text-sm font-medium text-muted-foreground transition-all hover:bg-background/50 hover:text-foreground data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm"
                >
                  <Scale size={16} className="shrink-0" />
                  <span>{tSettings("rates.tabSlabs")}</span>
                </TabsTrigger>
                <TabsTrigger
                  value="logs"
                  className="flex items-center gap-1.5 rounded-md px-4 py-1.5 text-xs md:text-sm font-medium text-muted-foreground transition-all hover:bg-background/50 hover:text-foreground data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm"
                >
                  <History size={16} className="shrink-0" />
                  <span>{tSettings("rates.tabLogs")}</span>
                </TabsTrigger>
              </TabsList>
            </div>
          )}

          <CardContent className="px-6 pb-6 pt-6">
            <TabsContent value="info" className="mt-0 outline-none">
              <GeneralInfoTab
                control={control}
                register={register}
                errors={errors}
                watch={watch}
                setValue={setValue}
                isCreate={isCreate}
                tSettings={tSettings}
                customerGroups={customerGroups ?? undefined}
                status={formData.status}
              />
            </TabsContent>

            {!isCreate && (
              <>
                <TabsContent value="slabs" className="mt-0 outline-none">
                  <SlabsTab
                    formData={formData}
                    slabs={slabs}
                    setSlabs={setSlabs}
                    tSettings={tSettings}
                  />
                </TabsContent>

                <TabsContent value="logs" className="mt-0 outline-none">
                  <LogsTab logs={logs} loadingLogs={loadingLogs} tSettings={tSettings} />
                </TabsContent>
              </>
            )}
          </CardContent>
        </Card>
      </Tabs>
    </div>
  );
}
